---
- name: restart gitlab
  service:
    name: "{{ docker_gitlab_service_name }}"
    state: restarted

- name: enable gitlab
  systemd:
    name: "{{ docker_gitlab_service_name }}"
    state: started
    enabled: yes
    daemon_reload: yes
